### ISSUE TITLE
How should I detect ParsedGroup?

### ISSUE THREAD

**Issue by RShergold** [jackbearheart/email-addresses#41]
Hey, thanks for the great module!

I have a minor issue that may just be a type definitions thing.
The following code in typescript:

```ts
function getAddress(headerString: string): string | null {
  const parsedAddress = emailAddresses.parseOneAddress(headerString);
  if (parsedAddress) {
    return parsedAddress.address;
  }
  return null;
}
```
Gives me the warning `Property 'address' does not exist on type 'ParsedGroup'`

It looks like all functions return `ParsedMailbox | ParsedGroup` (array of or single item) so this means two things.
1. It does not explicitly tell me that the result may be null
2. It does not guarantee that if there is a result, it will contain the email address.

My question is, how do I detect that it is not a `ParsedGroup` type and under what circumstances would `ParsedGroup` be returned instead of `ParsedMailbox` (or an array of ParsedMailbox).

**Comment by JakeSidSmith** [comment]
Looks to me like the types for `parseOneAddress` are incorrect as it only ever returns a `ParsedMailbox` (single address) or `null` (for invalid addresses & which is not included in the types).

The types should instead be:

```typescript
function parseOneAddress(input: string | Options): ParsedMailbox | null;
```

Correct me if I've missed some case where `parseOneAddress` returns more than one address.

Here's what I ran to check the output: https://gist.github.com/JakeSidSmith/7682c55c902867e60854be036e860547

**Comment by jackbearheart** [comment]
Hey, thanks for the issue.

First off, I'm not using the typescript definitions myself, so I'm happy to take suggestions and PRs on how to make them better.

Second, let me explain what a "ParsedMailbox" and a "ParsedGroup" are. These terms I am pulling from the RFCs' productions on which email-addresses is based. `parseOneAddress` is a helper that tries to parse an `address-list`, but expects a list of size one, and returns that. An `address-list` is made up of `address`es which can be either a `mailbox` or a `group`. The problem here is that you could have an address-list that has one `address` in it, which is a `group`, which could be made of multiple mailboxes! Technically `parseOneAddress` is giving you one `address`, but this isn't intuitively the thing you expect. See my example below.

I think the easiest thing to do here (please tell me if this is what you want) is to change the type of these functions so that they can all possibly return `null`.

But maybe we should also add a `parseOneMailbox` function, which is what people probably want most of the time.

Here's some examples to show you what I'm talking about:
```
> addrs('My fun group: foo@example.com;')
{ ast: 
   { name: 'address-list',
     tokens: 'My fun group: foo@example.com;',
     semantic: 'My fun group:foo@example.com;',
     children: [ [Object] ] },
  addresses: 
   [ { node: [Object],
       parts: [Object],
       type: 'group',
       name: 'My fun group',
       addresses: [Array] } ] }
> addrs.parseOneAddress('My fun group: foo@example.com;')
{ parts: 
   { name: 
      { name: 'display-name',
        tokens: 'My fun group',
        semantic: 'My fun group',
        children: [Array] } },
  type: 'group',
  name: 'My fun group',
  addresses: 
   [ { node: [Object],
       parts: [Object],
       type: 'mailbox',
       name: null,
       address: 'foo@example.com',
       local: 'foo',
       domain: 'example.com',
       groupName: null } ] }
> addrs.parseOneAddress('foo@example.com')
{ parts: 
   { name: null,
     address: 
      { name: 'addr-spec',
        tokens: 'foo@example.com',
        semantic: 'foo@example.com',
        children: [Array] },
     local: 
      { name: 'local-part',
        tokens: 'foo',
        semantic: 'foo',
        children: [Array] },
     domain: 
      { name: 'domain',
        tokens: 'example.com',
        semantic: 'example.com',
        children: [Array] },
     comments: [] },
  type: 'mailbox',
  name: null,
  address: 'foo@example.com',
  local: 'foo',
  domain: 'example.com',
  groupName: null }
```

**Comment by jackbearheart** [comment]
If I didn't make it clear, a `ParsedGroup` is not just a list of `ParsedMailbox`es; it's a separate thing conceptually, because it has a name. It looks like `This is the name of the group: firstperson@example.com, secondperson@example.com;`.

**Comment by sciyoshi** [comment]
I ran into a similar issue - I opened PR https://github.com/jackbearheart/email-addresses/pull/45 that allows you to safely use the `type` as a discriminant:
```
const addr = parseOneAddress(value);
if (addr && addr.type == "mailbox") {
  return addr.address;
}
```

**Comment by jackbearheart** [comment]
I merged sciyoshi's PR.
